"use strict";
exports.__esModule = true;
console.clear();
var person_1 = require("./person");
var calendar_1 = require("./calendar");
var persona1 = new person_1.Person("Pablo", "22", "calle Isla, 4");
var persona2 = new person_1.Person("Marta", "28", "calle Flor, 5");
var persona3 = new person_1.Person("Sara", "35", "calle Palmera, 24");
var agenda = new calendar_1.Agenda([persona1, persona2, persona3]);
console.log("Sus nombre es: " + persona1.name);
console.log("Los datos de su agenda son: " + agenda.printCalendar());
