"use strict";
exports.__esModule = true;
console.clear();
var library_1 = require("./library");
var book_1 = require("./book");
var book1 = new book_1.Book("Introducción a Javascript", 233, "2344433-BC23333", "Joseph Smith", "Now Editions");
var book2 = new book_1.Book("Pulgarcita", 50, "2343477473-BD23333", "Romalgo", "SM");
var book3 = new book_1.Book("Bambi", 50, "23473743-BD23333", "Pedro Jimenez", "SM");
var book4 = new book_1.Book("Peter Pan", 50, "23473743-BD23333", "Joseph Smith", "SM");
var library1 = new library_1.Library([book1, book2, book3, book4], "calle Fin del Mundo, 3, Madrid", "Miguel Cebrera");
//console.log(library1);
console.log(library1.getAdress() + "\n" + library1.getManager() + "\n" + library1.getNumberOfBooks());
console.log(library1.toString());
console.log("Los libros que contienen el autor Joseph Smith son: " + "\n" + library1.findByAuthor("Joseph Smith") + "\n");
console.log("Los libros de la editorial SM son: \n" + library1.findByEditorial("SM"));
